spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.liquibase.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Compression des réponses GET
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/csv
server.compression.min-response-size=1024

