spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.liquibase.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 1. Empêche Spring de rediriger vers sa page /error par défaut
server.error.whitelabel.enabled=false
# Force Spring à lever une exception si l'URL n'existe pas
spring.mvc.throw-exception-if-no-handler-found=true
# Désactive la recherche de ressources statiques pour éviter les conflits
spring.web.resources.add-mappings=false


# Compression des réponses GET
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/csv
server.compression.min-response-size=1024

# JWT
jwt.secret=3f8a2b1c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a
jwt.expiration=86400000